
(* Mostre como representar a precedência 
   entre operadores lógicos e relacionais.
   ---------------------------------------

   expr && expr
   expr || expr
   
   !expr

   expr > expr
   expr >= expr
   expr < expr
   expr <= expr
   expr != expr
   expr == expr
   
   --------------------------------------- *)

rel ::= 